### ISSUE TITLE
When uploading, copy the returned URL to the clipboard 

### ISSUE THREAD

**Issue by cswimr** [Stef-00012/Zipline-Upload-Extension#5]
Title explains this feature request. Currently, when you upload a file through the context menu, you get this notification:  
![image](https://github.com/user-attachments/assets/a8c506b6-7d44-49b3-a135-e0162c917f6e)

The url in the notification, however, is not copied to the user's clipboard, so you have to open Zipline to copy the url. I think it'd be ideal if the url was copied to the user's clipboard, as that makes the extension far easier to use.

P.S. this is a cool project!

Edit: just noticed there's also a typo in the notification, `upload` should say `uploaded`

**Comment by Stef-00012** [comment]
in the next update it'll show a popup with the url and a copy button instead of notifications

i can't copy automatically cause i could manage to get access to `navigator.clipboard.writeText()` even with the `clipboardWrite` permission

**Comment by Stef-00012** [comment]
like that 
![image](https://github.com/user-attachments/assets/feac9920-82af-459a-8e5b-92e3306b7685)

**Comment by Stef-00012** [comment]
just pushed the update with the copy url popup
